// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nebula-live/ent/permission"
	"nebula-live/ent/role"
	"nebula-live/ent/rolepermission"
	"nebula-live/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RolePermissionCreate is the builder for creating a RolePermission entity.
type RolePermissionCreate struct {
	config
	mutation *RolePermissionMutation
	hooks    []Hook
}

// SetRoleID sets the "role_id" field.
func (_c *RolePermissionCreate) SetRoleID(v uint) *RolePermissionCreate {
	_c.mutation.SetRoleID(v)
	return _c
}

// SetPermissionID sets the "permission_id" field.
func (_c *RolePermissionCreate) SetPermissionID(v uint) *RolePermissionCreate {
	_c.mutation.SetPermissionID(v)
	return _c
}

// SetAssignedBy sets the "assigned_by" field.
func (_c *RolePermissionCreate) SetAssignedBy(v uint) *RolePermissionCreate {
	_c.mutation.SetAssignedBy(v)
	return _c
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_c *RolePermissionCreate) SetNillableAssignedBy(v *uint) *RolePermissionCreate {
	if v != nil {
		_c.SetAssignedBy(*v)
	}
	return _c
}

// SetAssignedAt sets the "assigned_at" field.
func (_c *RolePermissionCreate) SetAssignedAt(v time.Time) *RolePermissionCreate {
	_c.mutation.SetAssignedAt(v)
	return _c
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_c *RolePermissionCreate) SetNillableAssignedAt(v *time.Time) *RolePermissionCreate {
	if v != nil {
		_c.SetAssignedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RolePermissionCreate) SetID(v uint) *RolePermissionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetRole sets the "role" edge to the Role entity.
func (_c *RolePermissionCreate) SetRole(v *Role) *RolePermissionCreate {
	return _c.SetRoleID(v.ID)
}

// SetPermission sets the "permission" edge to the Permission entity.
func (_c *RolePermissionCreate) SetPermission(v *Permission) *RolePermissionCreate {
	return _c.SetPermissionID(v.ID)
}

// SetAssignerID sets the "assigner" edge to the User entity by ID.
func (_c *RolePermissionCreate) SetAssignerID(id uint) *RolePermissionCreate {
	_c.mutation.SetAssignerID(id)
	return _c
}

// SetNillableAssignerID sets the "assigner" edge to the User entity by ID if the given value is not nil.
func (_c *RolePermissionCreate) SetNillableAssignerID(id *uint) *RolePermissionCreate {
	if id != nil {
		_c = _c.SetAssignerID(*id)
	}
	return _c
}

// SetAssigner sets the "assigner" edge to the User entity.
func (_c *RolePermissionCreate) SetAssigner(v *User) *RolePermissionCreate {
	return _c.SetAssignerID(v.ID)
}

// Mutation returns the RolePermissionMutation object of the builder.
func (_c *RolePermissionCreate) Mutation() *RolePermissionMutation {
	return _c.mutation
}

// Save creates the RolePermission in the database.
func (_c *RolePermissionCreate) Save(ctx context.Context) (*RolePermission, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RolePermissionCreate) SaveX(ctx context.Context) *RolePermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RolePermissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RolePermissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RolePermissionCreate) defaults() {
	if _, ok := _c.mutation.AssignedAt(); !ok {
		v := rolepermission.DefaultAssignedAt()
		_c.mutation.SetAssignedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RolePermissionCreate) check() error {
	if _, ok := _c.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "RolePermission.role_id"`)}
	}
	if _, ok := _c.mutation.PermissionID(); !ok {
		return &ValidationError{Name: "permission_id", err: errors.New(`ent: missing required field "RolePermission.permission_id"`)}
	}
	if _, ok := _c.mutation.AssignedAt(); !ok {
		return &ValidationError{Name: "assigned_at", err: errors.New(`ent: missing required field "RolePermission.assigned_at"`)}
	}
	if len(_c.mutation.RoleIDs()) == 0 {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required edge "RolePermission.role"`)}
	}
	if len(_c.mutation.PermissionIDs()) == 0 {
		return &ValidationError{Name: "permission", err: errors.New(`ent: missing required edge "RolePermission.permission"`)}
	}
	return nil
}

func (_c *RolePermissionCreate) sqlSave(ctx context.Context) (*RolePermission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RolePermissionCreate) createSpec() (*RolePermission, *sqlgraph.CreateSpec) {
	var (
		_node = &RolePermission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rolepermission.Table, sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeUint))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.AssignedAt(); ok {
		_spec.SetField(rolepermission.FieldAssignedAt, field.TypeTime, value)
		_node.AssignedAt = value
	}
	if nodes := _c.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   rolepermission.RoleTable,
			Columns: []string{rolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PermissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   rolepermission.PermissionTable,
			Columns: []string{rolepermission.PermissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PermissionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssignerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   rolepermission.AssignerTable,
			Columns: []string{rolepermission.AssignerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AssignedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RolePermissionCreateBulk is the builder for creating many RolePermission entities in bulk.
type RolePermissionCreateBulk struct {
	config
	err      error
	builders []*RolePermissionCreate
}

// Save creates the RolePermission entities in the database.
func (_c *RolePermissionCreateBulk) Save(ctx context.Context) ([]*RolePermission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RolePermission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RolePermissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RolePermissionCreateBulk) SaveX(ctx context.Context) []*RolePermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RolePermissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RolePermissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
