// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"nebula-live/ent/predicate"
	"nebula-live/ent/userpushsetting"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserPushSettingDelete is the builder for deleting a UserPushSetting entity.
type UserPushSettingDelete struct {
	config
	hooks    []Hook
	mutation *UserPushSettingMutation
}

// Where appends a list predicates to the UserPushSettingDelete builder.
func (_d *UserPushSettingDelete) Where(ps ...predicate.UserPushSetting) *UserPushSettingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserPushSettingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserPushSettingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserPushSettingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userpushsetting.Table, sqlgraph.NewFieldSpec(userpushsetting.FieldID, field.TypeUint))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserPushSettingDeleteOne is the builder for deleting a single UserPushSetting entity.
type UserPushSettingDeleteOne struct {
	_d *UserPushSettingDelete
}

// Where appends a list predicates to the UserPushSettingDelete builder.
func (_d *UserPushSettingDeleteOne) Where(ps ...predicate.UserPushSetting) *UserPushSettingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserPushSettingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userpushsetting.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserPushSettingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
