// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"nebula-live/ent/predicate"
	"nebula-live/ent/user"
	"nebula-live/ent/userpushsetting"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserPushSettingQuery is the builder for querying UserPushSetting entities.
type UserPushSettingQuery struct {
	config
	ctx        *QueryContext
	order      []userpushsetting.OrderOption
	inters     []Interceptor
	predicates []predicate.UserPushSetting
	withUser   *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserPushSettingQuery builder.
func (_q *UserPushSettingQuery) Where(ps ...predicate.UserPushSetting) *UserPushSettingQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *UserPushSettingQuery) Limit(limit int) *UserPushSettingQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *UserPushSettingQuery) Offset(offset int) *UserPushSettingQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *UserPushSettingQuery) Unique(unique bool) *UserPushSettingQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *UserPushSettingQuery) Order(o ...userpushsetting.OrderOption) *UserPushSettingQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *UserPushSettingQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userpushsetting.Table, userpushsetting.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, userpushsetting.UserTable, userpushsetting.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserPushSetting entity from the query.
// Returns a *NotFoundError when no UserPushSetting was found.
func (_q *UserPushSettingQuery) First(ctx context.Context) (*UserPushSetting, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userpushsetting.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *UserPushSettingQuery) FirstX(ctx context.Context) *UserPushSetting {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserPushSetting ID from the query.
// Returns a *NotFoundError when no UserPushSetting ID was found.
func (_q *UserPushSettingQuery) FirstID(ctx context.Context) (id uint, err error) {
	var ids []uint
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userpushsetting.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *UserPushSettingQuery) FirstIDX(ctx context.Context) uint {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserPushSetting entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserPushSetting entity is found.
// Returns a *NotFoundError when no UserPushSetting entities are found.
func (_q *UserPushSettingQuery) Only(ctx context.Context) (*UserPushSetting, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userpushsetting.Label}
	default:
		return nil, &NotSingularError{userpushsetting.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *UserPushSettingQuery) OnlyX(ctx context.Context) *UserPushSetting {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserPushSetting ID in the query.
// Returns a *NotSingularError when more than one UserPushSetting ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *UserPushSettingQuery) OnlyID(ctx context.Context) (id uint, err error) {
	var ids []uint
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userpushsetting.Label}
	default:
		err = &NotSingularError{userpushsetting.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *UserPushSettingQuery) OnlyIDX(ctx context.Context) uint {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserPushSettings.
func (_q *UserPushSettingQuery) All(ctx context.Context) ([]*UserPushSetting, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserPushSetting, *UserPushSettingQuery]()
	return withInterceptors[[]*UserPushSetting](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *UserPushSettingQuery) AllX(ctx context.Context) []*UserPushSetting {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserPushSetting IDs.
func (_q *UserPushSettingQuery) IDs(ctx context.Context) (ids []uint, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(userpushsetting.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *UserPushSettingQuery) IDsX(ctx context.Context) []uint {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *UserPushSettingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*UserPushSettingQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *UserPushSettingQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *UserPushSettingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *UserPushSettingQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserPushSettingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *UserPushSettingQuery) Clone() *UserPushSettingQuery {
	if _q == nil {
		return nil
	}
	return &UserPushSettingQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]userpushsetting.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.UserPushSetting{}, _q.predicates...),
		withUser:   _q.withUser.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UserPushSettingQuery) WithUser(opts ...func(*UserQuery)) *UserPushSettingQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID uint `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserPushSetting.Query().
//		GroupBy(userpushsetting.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *UserPushSettingQuery) GroupBy(field string, fields ...string) *UserPushSettingGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserPushSettingGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = userpushsetting.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID uint `json:"user_id,omitempty"`
//	}
//
//	client.UserPushSetting.Query().
//		Select(userpushsetting.FieldUserID).
//		Scan(ctx, &v)
func (_q *UserPushSettingQuery) Select(fields ...string) *UserPushSettingSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &UserPushSettingSelect{UserPushSettingQuery: _q}
	sbuild.label = userpushsetting.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserPushSettingSelect configured with the given aggregations.
func (_q *UserPushSettingQuery) Aggregate(fns ...AggregateFunc) *UserPushSettingSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *UserPushSettingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !userpushsetting.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *UserPushSettingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserPushSetting, error) {
	var (
		nodes       = []*UserPushSetting{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserPushSetting).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserPushSetting{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *UserPushSetting, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *UserPushSettingQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*UserPushSetting, init func(*UserPushSetting), assign func(*UserPushSetting, *User)) error {
	ids := make([]uint, 0, len(nodes))
	nodeids := make(map[uint][]*UserPushSetting)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *UserPushSettingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *UserPushSettingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(userpushsetting.Table, userpushsetting.Columns, sqlgraph.NewFieldSpec(userpushsetting.FieldID, field.TypeUint))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userpushsetting.FieldID)
		for i := range fields {
			if fields[i] != userpushsetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(userpushsetting.FieldUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *UserPushSettingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(userpushsetting.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = userpushsetting.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserPushSettingGroupBy is the group-by builder for UserPushSetting entities.
type UserPushSettingGroupBy struct {
	selector
	build *UserPushSettingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *UserPushSettingGroupBy) Aggregate(fns ...AggregateFunc) *UserPushSettingGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *UserPushSettingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserPushSettingQuery, *UserPushSettingGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *UserPushSettingGroupBy) sqlScan(ctx context.Context, root *UserPushSettingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserPushSettingSelect is the builder for selecting fields of UserPushSetting entities.
type UserPushSettingSelect struct {
	*UserPushSettingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *UserPushSettingSelect) Aggregate(fns ...AggregateFunc) *UserPushSettingSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *UserPushSettingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserPushSettingQuery, *UserPushSettingSelect](ctx, _s.UserPushSettingQuery, _s, _s.inters, v)
}

func (_s *UserPushSettingSelect) sqlScan(ctx context.Context, root *UserPushSettingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
