// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nebula-live/ent/user"
	"nebula-live/ent/userpushsetting"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserPushSettingCreate is the builder for creating a UserPushSetting entity.
type UserPushSettingCreate struct {
	config
	mutation *UserPushSettingMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *UserPushSettingCreate) SetUserID(v uint) *UserPushSettingCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *UserPushSettingCreate) SetProvider(v userpushsetting.Provider) *UserPushSettingCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *UserPushSettingCreate) SetEnabled(v bool) *UserPushSettingCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *UserPushSettingCreate) SetNillableEnabled(v *bool) *UserPushSettingCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetDeviceID sets the "device_id" field.
func (_c *UserPushSettingCreate) SetDeviceID(v string) *UserPushSettingCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetDeviceName sets the "device_name" field.
func (_c *UserPushSettingCreate) SetDeviceName(v string) *UserPushSettingCreate {
	_c.mutation.SetDeviceName(v)
	return _c
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_c *UserPushSettingCreate) SetNillableDeviceName(v *string) *UserPushSettingCreate {
	if v != nil {
		_c.SetDeviceName(*v)
	}
	return _c
}

// SetSettings sets the "settings" field.
func (_c *UserPushSettingCreate) SetSettings(v map[string]interface{}) *UserPushSettingCreate {
	_c.mutation.SetSettings(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserPushSettingCreate) SetCreatedAt(v time.Time) *UserPushSettingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserPushSettingCreate) SetNillableCreatedAt(v *time.Time) *UserPushSettingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserPushSettingCreate) SetUpdatedAt(v time.Time) *UserPushSettingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserPushSettingCreate) SetNillableUpdatedAt(v *time.Time) *UserPushSettingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserPushSettingCreate) SetID(v uint) *UserPushSettingCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserPushSettingCreate) SetUser(v *User) *UserPushSettingCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserPushSettingMutation object of the builder.
func (_c *UserPushSettingCreate) Mutation() *UserPushSettingMutation {
	return _c.mutation
}

// Save creates the UserPushSetting in the database.
func (_c *UserPushSettingCreate) Save(ctx context.Context) (*UserPushSetting, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserPushSettingCreate) SaveX(ctx context.Context) *UserPushSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPushSettingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPushSettingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserPushSettingCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := userpushsetting.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userpushsetting.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userpushsetting.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserPushSettingCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserPushSetting.user_id"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "UserPushSetting.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := userpushsetting.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UserPushSetting.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "UserPushSetting.enabled"`)}
	}
	if _, ok := _c.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "UserPushSetting.device_id"`)}
	}
	if v, ok := _c.mutation.DeviceID(); ok {
		if err := userpushsetting.DeviceIDValidator(v); err != nil {
			return &ValidationError{Name: "device_id", err: fmt.Errorf(`ent: validator failed for field "UserPushSetting.device_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DeviceName(); ok {
		if err := userpushsetting.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`ent: validator failed for field "UserPushSetting.device_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserPushSetting.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserPushSetting.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserPushSetting.user"`)}
	}
	return nil
}

func (_c *UserPushSettingCreate) sqlSave(ctx context.Context) (*UserPushSetting, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserPushSettingCreate) createSpec() (*UserPushSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &UserPushSetting{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userpushsetting.Table, sqlgraph.NewFieldSpec(userpushsetting.FieldID, field.TypeUint))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(userpushsetting.FieldProvider, field.TypeEnum, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(userpushsetting.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.DeviceID(); ok {
		_spec.SetField(userpushsetting.FieldDeviceID, field.TypeString, value)
		_node.DeviceID = value
	}
	if value, ok := _c.mutation.DeviceName(); ok {
		_spec.SetField(userpushsetting.FieldDeviceName, field.TypeString, value)
		_node.DeviceName = value
	}
	if value, ok := _c.mutation.Settings(); ok {
		_spec.SetField(userpushsetting.FieldSettings, field.TypeJSON, value)
		_node.Settings = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userpushsetting.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userpushsetting.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userpushsetting.UserTable,
			Columns: []string{userpushsetting.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserPushSettingCreateBulk is the builder for creating many UserPushSetting entities in bulk.
type UserPushSettingCreateBulk struct {
	config
	err      error
	builders []*UserPushSettingCreate
}

// Save creates the UserPushSetting entities in the database.
func (_c *UserPushSettingCreateBulk) Save(ctx context.Context) ([]*UserPushSetting, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserPushSetting, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserPushSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserPushSettingCreateBulk) SaveX(ctx context.Context) []*UserPushSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPushSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPushSettingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
