// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nebula-live/ent/predicate"
	"nebula-live/ent/role"
	"nebula-live/ent/user"
	"nebula-live/ent/userrole"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserRoleUpdate is the builder for updating UserRole entities.
type UserRoleUpdate struct {
	config
	hooks    []Hook
	mutation *UserRoleMutation
}

// Where appends a list predicates to the UserRoleUpdate builder.
func (_u *UserRoleUpdate) Where(ps ...predicate.UserRole) *UserRoleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserRoleUpdate) SetUserID(v uint) *UserRoleUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserRoleUpdate) SetNillableUserID(v *uint) *UserRoleUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *UserRoleUpdate) SetRoleID(v uint) *UserRoleUpdate {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *UserRoleUpdate) SetNillableRoleID(v *uint) *UserRoleUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetAssignedBy sets the "assigned_by" field.
func (_u *UserRoleUpdate) SetAssignedBy(v uint) *UserRoleUpdate {
	_u.mutation.SetAssignedBy(v)
	return _u
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_u *UserRoleUpdate) SetNillableAssignedBy(v *uint) *UserRoleUpdate {
	if v != nil {
		_u.SetAssignedBy(*v)
	}
	return _u
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (_u *UserRoleUpdate) ClearAssignedBy() *UserRoleUpdate {
	_u.mutation.ClearAssignedBy()
	return _u
}

// SetAssignedAt sets the "assigned_at" field.
func (_u *UserRoleUpdate) SetAssignedAt(v time.Time) *UserRoleUpdate {
	_u.mutation.SetAssignedAt(v)
	return _u
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_u *UserRoleUpdate) SetNillableAssignedAt(v *time.Time) *UserRoleUpdate {
	if v != nil {
		_u.SetAssignedAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserRoleUpdate) SetUser(v *User) *UserRoleUpdate {
	return _u.SetUserID(v.ID)
}

// SetRole sets the "role" edge to the Role entity.
func (_u *UserRoleUpdate) SetRole(v *Role) *UserRoleUpdate {
	return _u.SetRoleID(v.ID)
}

// SetAssignerID sets the "assigner" edge to the User entity by ID.
func (_u *UserRoleUpdate) SetAssignerID(id uint) *UserRoleUpdate {
	_u.mutation.SetAssignerID(id)
	return _u
}

// SetNillableAssignerID sets the "assigner" edge to the User entity by ID if the given value is not nil.
func (_u *UserRoleUpdate) SetNillableAssignerID(id *uint) *UserRoleUpdate {
	if id != nil {
		_u = _u.SetAssignerID(*id)
	}
	return _u
}

// SetAssigner sets the "assigner" edge to the User entity.
func (_u *UserRoleUpdate) SetAssigner(v *User) *UserRoleUpdate {
	return _u.SetAssignerID(v.ID)
}

// Mutation returns the UserRoleMutation object of the builder.
func (_u *UserRoleUpdate) Mutation() *UserRoleMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserRoleUpdate) ClearUser() *UserRoleUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearRole clears the "role" edge to the Role entity.
func (_u *UserRoleUpdate) ClearRole() *UserRoleUpdate {
	_u.mutation.ClearRole()
	return _u
}

// ClearAssigner clears the "assigner" edge to the User entity.
func (_u *UserRoleUpdate) ClearAssigner() *UserRoleUpdate {
	_u.mutation.ClearAssigner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserRoleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserRoleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserRoleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserRoleUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRole.user"`)
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRole.role"`)
	}
	return nil
}

func (_u *UserRoleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userrole.Table, userrole.Columns, sqlgraph.NewFieldSpec(userrole.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AssignedAt(); ok {
		_spec.SetField(userrole.FieldAssignedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.UserTable,
			Columns: []string{userrole.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.UserTable,
			Columns: []string{userrole.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.RoleTable,
			Columns: []string{userrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.RoleTable,
			Columns: []string{userrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.AssignerTable,
			Columns: []string{userrole.AssignerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.AssignerTable,
			Columns: []string{userrole.AssignerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserRoleUpdateOne is the builder for updating a single UserRole entity.
type UserRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserRoleMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserRoleUpdateOne) SetUserID(v uint) *UserRoleUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserRoleUpdateOne) SetNillableUserID(v *uint) *UserRoleUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *UserRoleUpdateOne) SetRoleID(v uint) *UserRoleUpdateOne {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *UserRoleUpdateOne) SetNillableRoleID(v *uint) *UserRoleUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetAssignedBy sets the "assigned_by" field.
func (_u *UserRoleUpdateOne) SetAssignedBy(v uint) *UserRoleUpdateOne {
	_u.mutation.SetAssignedBy(v)
	return _u
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_u *UserRoleUpdateOne) SetNillableAssignedBy(v *uint) *UserRoleUpdateOne {
	if v != nil {
		_u.SetAssignedBy(*v)
	}
	return _u
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (_u *UserRoleUpdateOne) ClearAssignedBy() *UserRoleUpdateOne {
	_u.mutation.ClearAssignedBy()
	return _u
}

// SetAssignedAt sets the "assigned_at" field.
func (_u *UserRoleUpdateOne) SetAssignedAt(v time.Time) *UserRoleUpdateOne {
	_u.mutation.SetAssignedAt(v)
	return _u
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_u *UserRoleUpdateOne) SetNillableAssignedAt(v *time.Time) *UserRoleUpdateOne {
	if v != nil {
		_u.SetAssignedAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserRoleUpdateOne) SetUser(v *User) *UserRoleUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetRole sets the "role" edge to the Role entity.
func (_u *UserRoleUpdateOne) SetRole(v *Role) *UserRoleUpdateOne {
	return _u.SetRoleID(v.ID)
}

// SetAssignerID sets the "assigner" edge to the User entity by ID.
func (_u *UserRoleUpdateOne) SetAssignerID(id uint) *UserRoleUpdateOne {
	_u.mutation.SetAssignerID(id)
	return _u
}

// SetNillableAssignerID sets the "assigner" edge to the User entity by ID if the given value is not nil.
func (_u *UserRoleUpdateOne) SetNillableAssignerID(id *uint) *UserRoleUpdateOne {
	if id != nil {
		_u = _u.SetAssignerID(*id)
	}
	return _u
}

// SetAssigner sets the "assigner" edge to the User entity.
func (_u *UserRoleUpdateOne) SetAssigner(v *User) *UserRoleUpdateOne {
	return _u.SetAssignerID(v.ID)
}

// Mutation returns the UserRoleMutation object of the builder.
func (_u *UserRoleUpdateOne) Mutation() *UserRoleMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserRoleUpdateOne) ClearUser() *UserRoleUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearRole clears the "role" edge to the Role entity.
func (_u *UserRoleUpdateOne) ClearRole() *UserRoleUpdateOne {
	_u.mutation.ClearRole()
	return _u
}

// ClearAssigner clears the "assigner" edge to the User entity.
func (_u *UserRoleUpdateOne) ClearAssigner() *UserRoleUpdateOne {
	_u.mutation.ClearAssigner()
	return _u
}

// Where appends a list predicates to the UserRoleUpdate builder.
func (_u *UserRoleUpdateOne) Where(ps ...predicate.UserRole) *UserRoleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserRoleUpdateOne) Select(field string, fields ...string) *UserRoleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserRole entity.
func (_u *UserRoleUpdateOne) Save(ctx context.Context) (*UserRole, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserRoleUpdateOne) SaveX(ctx context.Context) *UserRole {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserRoleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserRoleUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRole.user"`)
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserRole.role"`)
	}
	return nil
}

func (_u *UserRoleUpdateOne) sqlSave(ctx context.Context) (_node *UserRole, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userrole.Table, userrole.Columns, sqlgraph.NewFieldSpec(userrole.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userrole.FieldID)
		for _, f := range fields {
			if !userrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AssignedAt(); ok {
		_spec.SetField(userrole.FieldAssignedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.UserTable,
			Columns: []string{userrole.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.UserTable,
			Columns: []string{userrole.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.RoleTable,
			Columns: []string{userrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.RoleTable,
			Columns: []string{userrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.AssignerTable,
			Columns: []string{userrole.AssignerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userrole.AssignerTable,
			Columns: []string{userrole.AssignerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserRole{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
