app:
  name: "nebula-live"
  version: "1.0.0"
  env: "development"

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database: "nebula_live"
  ssl_mode: "disable"
  max_idle_conns: 10
  max_open_conns: 30
  conn_max_lifetime: 30m

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5

log:
  level: "info"
  format: "json"
  output: "logs/app.log"
  max_size: 100
  max_age: 30
  max_backups: 10
  compress: true
  enable_color: true
  enable_console: true
  enable_file: true

jwt:
  secret: "your-secret-key"
  expires_in: "24h"

cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
  expose_headers:
    - "Content-Length"
  allow_credentials: false
  max_age: 86400